# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='albumn_logo',
            new_name='album_logo',
        ),
    ]
